
version: '2'
services:
  server:
    image: redash/redash:4.0.0-beta.b3690
    command: server
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_COOKIE_SECRET: veryverysecret
      REDASH_WEB_WORKERS: 4
    restart: always
  worker:
    image: redash/redash:4.0.0-beta.b3690
    command: scheduler
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      QUEUES: "queries,scheduled_queries,celery"
      WORKERS_COUNT: 2
    restart: always
  redis:
    image: redis:3.0-alpine
    restart: always
  postgres:
    image: postgres:9.5.6-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
    restart: always
    ports:
      - "5432:5432"
  clickhouse:
    image: yandex/clickhouse-server:1.1.54327
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
       - ./clickhouse-data:/var/lib/clickhouse
  mariadb:
    image: mariadb:10.3
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
       - ./mariadb-data:/var/lib/mysql
  nginx:
    image: redash/nginx:latest
    ports:
      - "80:80"
    depends_on:
      - server
    links:
      - server:redash
    restart: always
  gobuild:
    image: golang:1.9.4-alpine3.7
    volumes: 
      - .:/go/src/wrkr-t3chfest
    command: sh
    stdin_open: true
    tty: true
